kind: Pod
apiVersion: v1
metadata:
  name: emptydir-pod
spec:
  containers:
    - name: emptydir-pod-container
      image: busybox:latest
      ports:
        - containerPort: 80
      command:
        - /bin/sh
        - -c
        - |
          echo "Timestamp: $(date)" > /data/message.txt
          sleep 3600
      volumeMounts:
        - name: emptydir-vol
          mountPath: /data
  volumes:
    - name: emptydir-vol
      emptyDir: {}
