apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-probe
spec:
  containers:
    - name: pod-liveness-probe-container
      image: busybox:1.26
      command:
        [
          "/bin/sh",
          "-c",
          "touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600",
        ]
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        periodSeconds: 5
        failureThreshold: 3
