kind: Pod
apiVersion: v1
metadata:
  name: pod-req-limit
spec:
  containers:
    - name: pod-req-limit-contaimer
      image: busybox:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "250m"

