FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt --target /app/library

COPY . .


#USING DISTROLESS IMAGE -- VERY SMALL IN SIZE
FROM gcr.io/distroless/python3-debian12 AS deployer

WORKDIR /app

COPY --from=builder /app/library /app/library

COPY --from=builder /app .

ENV PYTHONPATH="/app/library"

EXPOSE 80

CMD ["run.py"]
